apiVersion: v1
kind: Service
metadata:
  name: flashtans-app
  namespace: flashtans
spec:
  type: NodePort
  selector:
    app: flashtans-app
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
