apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: flashtans
data:
  common.cnf: |
    [mysqld]
    bind-address=0.0.0.0

    gtid_mode=ON
    enforce_gtid_consistency=ON
    log_bin=mysql-bin
    binlog_format=ROW
    transaction_write_set_extraction=XXHASH64

    plugin_load_add=group_replication.so

    loose-group_replication_group_name="aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
    loose-group_replication_start_on_boot=ON
    loose-group_replication_recovery_get_public_key=ON
    loose-group_replication_bootstrap_group=OFF
    loose-group_replication_group_seeds="mysql-0.mysql-headless.flashtans.svc.cluster.local:33061,mysql-1.mysql-headless.flashtans.svc.cluster.local:33061,mysql-2.mysql-headless.flashtans.svc.cluster.local:33061"
    loose-group_replication_ip_allowlist="AUTOMATIC"
