apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: flashtans
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: CHANGE_ME
  MYSQL_DATABASE: flash_tans_db
  MYSQL_USER: flashtans
  MYSQL_PASSWORD: CHANGE_ME
